
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 4.0.30319.17020
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace LunchLunch
open System
open System.Web
open System.Web.UI

type  (* partial *)Default() = 
        [<DefaultValue(false)>]
        val mutable button1:System.Web.UI.WebControls.Button
